### ISSUE TITLE
pls jar

### ISSUE THREAD

**Issue by Gtafgu** [Guillaume351/Skywars_Nukkit#1]

**Comment by Guillaume351** [comment]
Hello,
I'm working on fixing a last few issues and I will make a jar available

**Comment by Guillaume351** [comment]
Here is a link available 24h for the jar file. Please comment again if you want an other link. Your game map have to be named "game-0", and if you have multiple one, "game-0", "game-1", "game-2"...

Here is the link : 
https://sharefiles.app/download/8b08d17405868e09f05044c8fff6afdd4285c024
